"""
Seed data for Boost Templates.

Run via: bench execute flamezo_backend.flamezo.services.boost_templates_seed.seed_boost_templates
"""
import frappe


TEMPLATES = [
	{
		"template_id": "hero_dish",
		"template_name": "The Hero Dish",
		"rank": 1,
		"is_active": 1,
		"best_for": "Restaurants with 1 standout item",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 1,
		"hook_formula": "Have you tried {dish} at {restaurant}?",
		"primary_text_template": "{area}'s worst-kept secret? The {dish} at {restaurant}. First time? Get ₹{offer} off. 📍 {area}",
		"headline_template": "₹{offer} off {dish}",
		"offer_type_description": "Flat ₹X off specific dish",
		"expected_ctr_low": 2.5,
		"expected_ctr_high": 4.0,
	},
	{
		"template_id": "bogo",
		"template_name": "The BOGO",
		"rank": 2,
		"is_active": 1,
		"best_for": "Groups, couples",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Bring someone. We'll feed them free.",
		"primary_text_template": "Bring someone to {restaurant} and we'll feed them free. Buy 1 Get 1 on starters. 📍 {area}",
		"headline_template": "BOGO at {restaurant}",
		"offer_type_description": "Buy 1 Get 1 starters",
		"expected_ctr_low": 2.0,
		"expected_ctr_high": 3.5,
	},
	{
		"template_id": "first_timer",
		"template_name": "The First Timer",
		"rank": 3,
		"is_active": 1,
		"best_for": "New restaurant, low awareness",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Your first visit is on us (almost)",
		"primary_text_template": "Your first visit to {restaurant} comes with ₹{offer} off. {cuisine} done right. 📍 {area}",
		"headline_template": "₹{offer} off first visit",
		"offer_type_description": "Flat ₹X off first bill",
		"expected_ctr_low": 1.8,
		"expected_ctr_high": 3.0,
	},
	{
		"template_id": "weekend_pull",
		"template_name": "The Weekend Pull",
		"rank": 4,
		"is_active": 1,
		"best_for": "Weekend traffic boost",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Your Saturday sorted",
		"primary_text_template": "Weekend craving? {restaurant} has you covered. Get ₹{offer} off this weekend. 📍 {area}",
		"headline_template": "Weekend deal ₹{offer} off",
		"offer_type_description": "Flat ₹X off on weekends",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.5,
	},
	{
		"template_id": "lunch_steal",
		"template_name": "The Lunch Steal",
		"rank": 5,
		"is_active": 1,
		"best_for": "Lunch-weak restaurants",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Lunch done right, at the right price",
		"primary_text_template": "Lunch at {restaurant} just got better. ₹{offer} off your meal. Quick, fresh, sorted. 📍 {area}",
		"headline_template": "Lunch ₹{offer} off",
		"offer_type_description": "Flat ₹X off lunch orders",
		"expected_ctr_low": 2.0,
		"expected_ctr_high": 3.0,
	},
	{
		"template_id": "festive",
		"template_name": "The Festive",
		"rank": 6,
		"is_active": 1,
		"best_for": "Seasonal campaigns",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Celebrate at {restaurant}",
		"primary_text_template": "This season, celebrate at {restaurant}. ₹{offer} off your table. {cuisine} at its finest. 📍 {area}",
		"headline_template": "₹{offer} off this season",
		"offer_type_description": "Flat ₹X off seasonal special",
		"expected_ctr_low": 2.0,
		"expected_ctr_high": 4.0,
	},
	{
		"template_id": "review_bait",
		"template_name": "The Review Bait",
		"rank": 7,
		"is_active": 1,
		"best_for": "Restaurants with good ratings",
		"cta_type": "LEARN_MORE",
		"requires_hero_dish": 0,
		"hook_formula": "Rated top by foodies near you",
		"primary_text_template": "Foodies in {area} love {restaurant}. Try it yourself — ₹{offer} off your first bill. {cuisine}.",
		"headline_template": "Top-rated + ₹{offer} off",
		"offer_type_description": "Flat ₹X off to try",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.5,
	},
	{
		"template_id": "group_deal",
		"template_name": "The Group Deal",
		"rank": 8,
		"is_active": 1,
		"best_for": "Family restaurants",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Table for 4? We've got a deal.",
		"primary_text_template": "Bring the crew to {restaurant}. ₹{offer} off when you dine with friends. 📍 {area}",
		"headline_template": "Group deal ₹{offer} off",
		"offer_type_description": "Flat ₹X off for groups",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.0,
	},
	{
		"template_id": "happy_hour",
		"template_name": "The Happy Hour",
		"rank": 9,
		"is_active": 1,
		"best_for": "Bars, cafes",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "3-6 PM is the sweet spot",
		"primary_text_template": "3-6 PM at {restaurant} hits different. ₹{offer} off during happy hour. 📍 {area}",
		"headline_template": "Happy hour ₹{offer} off",
		"offer_type_description": "Flat ₹X off during happy hour",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.5,
	},
	{
		"template_id": "comeback",
		"template_name": "The Comeback",
		"rank": 10,
		"is_active": 1,
		"best_for": "Retargeting existing customers",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 0,
		"hook_formula": "Haven't visited in a while?",
		"primary_text_template": "It's been a while since you visited {restaurant}. Here's ₹{offer} off to welcome you back. 📍 {area}",
		"headline_template": "₹{offer} off — come back!",
		"offer_type_description": "Flat ₹X off loyalty reward",
		"expected_ctr_low": 2.0,
		"expected_ctr_high": 3.0,
	},
	{
		"template_id": "new_item",
		"template_name": "The New Item",
		"rank": 11,
		"is_active": 1,
		"best_for": "Menu updates",
		"cta_type": "LEARN_MORE",
		"requires_hero_dish": 1,
		"hook_formula": "Just added to the menu",
		"primary_text_template": "New on the menu at {restaurant}: {dish}. Be the first to try it — ₹{offer} off. 📍 {area}",
		"headline_template": "New: {dish} ₹{offer} off",
		"offer_type_description": "Flat ₹X off new menu item",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.0,
	},
	{
		"template_id": "chefs_pick",
		"template_name": "The Chef's Pick",
		"rank": 12,
		"is_active": 1,
		"best_for": "Premium restaurants",
		"cta_type": "GET_OFFER",
		"requires_hero_dish": 1,
		"hook_formula": "Our chef's favorite. Now yours.",
		"primary_text_template": "The chef at {restaurant} recommends the {dish}. Try it with ₹{offer} off. 📍 {area}",
		"headline_template": "Chef's pick ₹{offer} off",
		"offer_type_description": "Flat ₹X off chef's special",
		"expected_ctr_low": 1.5,
		"expected_ctr_high": 2.5,
	},
]


def seed_boost_templates():
	"""Insert or update all Boost Templates. Safe to run multiple times."""
	for t in TEMPLATES:
		if frappe.db.exists("Boost Template", t["template_id"]):
			doc = frappe.get_doc("Boost Template", t["template_id"])
			doc.update(t)
			doc.save(ignore_permissions=True)
		else:
			doc = frappe.get_doc({"doctype": "Boost Template", **t})
			doc.insert(ignore_permissions=True)
	frappe.db.commit()
	print(f"Seeded {len(TEMPLATES)} Boost Templates.")
